server:
  port: 8766

spring:
  application:
    name: config-server
  security:
    user:
      name: root
      password: abc123
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chocolatecw/SpringCloudConfig # 配置文件所在仓库地址
          search-paths: config         # 配置文件所在根目录
          #username:             # Github 等产品的登录账号
          #password:             # Github 等产品的登录密码
          #default-label: master # 配置文件分支

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:abc123@localhost:8761/eureka/
















